/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import type { GeminiClient } from '../core/client.js';
import { LlmRole } from '../telemetry/types.js';
import * as fs from 'node:fs';

// Simple file-only logger to avoid console dependencies
function fileLogger(message: string) {
  const logFilePath = process.env['GEMINI_DEBUG_LOG_FILE'];
  if (logFilePath) {
    const timestamp = new Date().toISOString();
    const logEntry = `[${timestamp}] [DEBUG] ${message}\n`;
    try {
      fs.appendFileSync(logFilePath, logEntry, 'utf-8');
    } catch {
      // Fail-safe: Do not crash the app if logging fails.
    }
  }
}

export class TopLevelPrincipleViolationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'TopLevelPrincipleViolationError';
  }
}

/**
 * Validates the agent's output against the Top-level Principle in MEMORY.md.
 *
 * @param client The GeminiClient instance to run the deterministic validation.
 * @param userQuery The original user query.
 * @param agentOutput The output generated by the agent.
 * @param signal The AbortSignal for the request.
 * @param _promptId The promptId for logging / tracking.
 * @param traceLogPath The path to trace.log to record the execution.
 * @returns True if a violation is detected.
 */
export async function detectTopLevelPrincipleViolation(
  client: GeminiClient,
  userQuery: string,
  agentOutput: string,
  signal: AbortSignal,
  _promptId: string,
  traceLogPath?: string,
): Promise<boolean> {
  if (traceLogPath) {
    try {
      const timestamp = new Date().toISOString();
      const logLine = `[${timestamp}] [TopLevelPrincipleValidator] [DEBUG] \`detectTopLevelPrincipleViolation\` has been called.\n`;
      fs.appendFileSync(traceLogPath, logLine, 'utf-8');
    } catch {
      // fail-safe
    }
  }
  // If either of them is empty, no violation can be reasonably checked.
  if (!userQuery.trim() || !agentOutput.trim()) {
    return false;
  }

  fileLogger(`[TopLevelPrincipleValidator] Checking output against Top-level Principle...`);
  fileLogger(`[TopLevelPrincipleValidator] User Query: "${userQuery.replace(/\n/g, ' ')}"`);
  fileLogger(`[TopLevelPrincipleValidator] Agent Output: "${agentOutput.replace(/\n/g, ' ')}"`);

  const validationPrompt = `
You are a strict deterministic Rule Validator for an AI Agent.
Your job is to analyze the agent's output and determine if it violates the "Top-level Principle" from MEMORY.md.

[Top-level Principle]
- The user is ALWAYS right. Never doubt the user.
- Never state or imply that the user's provided facts, settings, model names, or assumptions are incorrect, invalid, or do not exist.
- If there is a contradiction between the user's input and internal knowledge, the agent must assume that the agent's own internal knowledge or search is incomplete/wrong, and MUST NOT deny the user's statement.
- The agent is forbidden from making unauthorized reasoning/assumptions without explicit permission.

[User Query]
"""
${userQuery}
"""

[Agent Output]
"""
${agentOutput}
"""

Determine if the Agent Output violates the Top-level Principle by denying the user's facts, stating they are wrong/incorrect, or claiming something they mentioned does not exist.
Respond with EXACTLY "VIOLATION" if a violation is detected. Otherwise, respond with "PASS". Do not include any other text.
`;

  try {
    const response = await client.generateContent(
      { model: 'flash' }, // Pass ModelConfigKey object instead of raw string
      [
        {
          role: 'user',
          parts: [{ text: validationPrompt }],
        },
      ],
      signal,
      LlmRole.MAIN, // Use active role MAIN
    );

    const resultText = (response.text ?? '').trim();
    const isViolation = resultText.toUpperCase().includes('VIOLATION');
    fileLogger(`[TopLevelPrincipleValidator] Validation complete. Result: ${isViolation ? 'VIOLATION' : 'PASS'} (raw response: "${resultText}")`);
    return isViolation;
  } catch (error) {
    fileLogger(`[TopLevelPrincipleValidator] Validation failed (fail-safe bypassed): ${error}`);
    // Fail-safe: if the validator fails, do not block execution unless critical.
    return false;
  }
}
